---
kind: pipeline
name: build
platform:
  os: linux
  arch: amd64

steps:
  - name: build-base
    image: plugins/docker
    settings:
      username: brandonkal
      password:
        from_secret: docker_password
      repo: brandonkal/docker-polyglot
      context: './base'
      dockerfile: './base/Dockerfile'
      tags: base
  - name: build-lang
    image: plugins/docker
    settings:
      username: brandonkal
      password:
        from_secret: docker_password
      repo: brandonkal/docker-polyglot
      context: './languages'
      dockerfile: './languages/Dockerfile'
      tags: lang
