---
kind: pipeline
name: build
platform:
  os: linux
  arch: amd64

steps:
  - name: build-base
    image: plugins/docker
    settings:
      username: brandonkal
      password:
        from_secret: docker_password
      repo: brandonkal/docker-polyglot
      context: ./base
      tags: latest
